"""Generate command help from the actual Typer tree, including nested commands."""

from pathlib import Path

from typer.main import get_command
from typer.testing import CliRunner

from cli.main import app


def main():
    runner = CliRunner()
    output = [
        "# Command reference\n",
        "Generated by `python -m scripts.generate_docs`. Global flags may appear before or after subcommands: `--json`, `--quiet`, `--yes`, `--no-color`, `--debug`.\n",
    ]

    def visit(command, path):
        result = runner.invoke(
            app, [*path, "--help"], color=False, terminal_width=100, prog_name="flunky"
        )
        if result.exit_code:
            raise RuntimeError(result.output)
        output.extend(
            [f"## flunky {' '.join(path)}\n", "```text\n" + result.output.rstrip() + "\n```\n"]
        )
        for name, child in getattr(command, "commands", {}).items():
            if not child.hidden:
                visit(child, [*path, name])

    visit(get_command(app), [])
    Path("docs/COMMANDS.md").write_text("\n".join(output), encoding="utf-8")


if __name__ == "__main__":
    main()
